name: Releases

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: choco install --yes pandoc
      - run: pandoc --standalone --embed-resources --output=README.html README.md

      - uses: ncipollo/release-action@v1
        with:
          tag: "v0.1"
          artifacts: README.html
          allowUpdates: true
