name: Releases

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo hi
          sudo apt install -y pandoc
          mkdir yeah
          pandoc --standalone --embed-resources --output=./yeah/README.html README.md

      - uses: ncipollo/release-action@v1
        with:
          tag: "v0.0.5"
          artifacts: yeah/README.html
          allowUpdates: true
