name: Releases

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: docker://pandoc/core
        with:
          args: "--help" # gets appended to pandoc command
          # args: "--standalone --embed-resources --output README.html README.md" # gets appended to pandoc command

      # - uses: ncipollo/release-action@v1
      #   with:
      #     tag: "v0.1"
      #     artifacts: README.html
      #     allowUpdates: true
