name: Releases

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          my_version="$(cat package.json | jq -r '.version')"
          echo "MY_VERSION=$my_version" >>"$GITHUB_ENV"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: package.json
          bodyFile: "body.md"
          tag: "main"
          commit: "main"
