name: Releases

on:
  workflow_dispatch:
  push:

jobs:
  build:
    steps:
      - uses: docker://pandoc/core
        with:
          args: "--help"

      # - uses: ncipollo/release-action@v1
      #   with:
      #     tag: "v0.1"
      #     artifacts: README.html
      #     allowUpdates: true
