name: Releases

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          my_version="$(cat package.json | jq -r '.version')"
          echo "MY_VERSION=$my_version" >>"$GITHUB_ENV"

# Check if release exists
# Check if release version equals npm registry version

      - uses: ncipollo/release-action@v1
        with:
          artifacts: package.json
