name: Releases

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
        shell: zsh
      # - run: |
      #     mkdir yeah
      #     choco install --yes pandoc
      #     pandoc --standalone --embed-resources --output=./yeah/README.html README.md

      # - uses: ncipollo/release-action@v1
      #   with:
      #     tag: "v0.1"
      #     artifacts: yeah/README.html
      #     allowUpdates: true
