name: Releases

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir yeah
          choco install --yes pandoc
          pandoc --standalone --embed-resources --output=./yeah/README.html README.md

      - uses: ncipollo/release-action@v1
        with:
          tag: "v0.1"
          artifacts: yeah/README.html
          allowUpdates: true
